// Verifies FeatureCalculator reproduces the EXACT pandas feature formulas used
// to build the training feature store (FirstRRC.ipynb, Section 3). Reads
// tests/feature_fixture.json (generated by gen_expected.py), replays the bars
// (plus companion SPY/AMD closes) through the calculator, and compares every
// feature at the last bar against the ground truth.

#include <chrono>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

#include "engine/FeatureCalculator.hpp"

using nlohmann::json;
using hermes::Bar;
using hermes::FeatureCalculator;

static Bar toBar(const json& b, const std::string& sym) {
    Bar bar;
    bar.time = std::chrono::system_clock::from_time_t(b.at("t").get<long>());
    bar.open = b.at("open");
    bar.high = b.at("high");
    bar.low = b.at("low");
    bar.close = b.at("close");
    bar.volume = b.at("volume");
    bar.symbol = sym;
    return bar;
}

int main(int argc, char* argv[]) {
    const std::string path =
        argc > 1 ? argv[1] : "tests/feature_fixture.json";

    std::ifstream in(path);
    if (!in) {
        std::fprintf(stderr, "could not open fixture '%s'\n", path.c_str());
        return 2;
    }
    json fx;
    in >> fx;

    std::vector<Bar> bars, spy, amd;
    for (const auto& b : fx.at("bars")) bars.push_back(toBar(b, "NVDA"));
    for (const auto& b : fx.at("spy")) spy.push_back(toBar(b, "SPY"));
    for (const auto& b : fx.at("amd")) amd.push_back(toBar(b, "AMD"));

    // Every feature the fixture provides ground truth for (all single-symbol,
    // cross-asset and time features — the 48 of the 55-feature contract that
    // do not require the HMM artifact). Order is irrelevant; compared by name.
    const std::vector<std::string> features = {
        "logret_1", "logret_5", "logret_15", "logret_30", "logret_60",
        "vol_5", "vol_10", "vol_20", "vol_60", "overnight_gap",
        "intraday_range", "rsi_7", "rsi_14", "rsi_21", "roc_5", "roc_15",
        "roc_30", "stoch_k", "stoch_d", "ema_9_dist", "ema_21_dist",
        "ema_50_dist", "ema_200_dist", "macd_line", "macd_signal", "macd_hist",
        "macd_hist_slope", "adx_14", "bb_pctb", "bb_bandwidth", "bb_squeeze",
        "zscore_20", "zscore_60", "dist_vwap", "vwap_z", "vol_ratio_20",
        "obv", "obv_slope", "vwpm", "adl", "adl_slope", "beta_spy_20",
        "corr_spy_20", "relstr_amd_20", "hour_sin", "hour_cos", "dow_sin",
        "dow_cos", "min_since_open", "min_to_close", "last_30_flag",
    };

    FeatureCalculator calc(features, /*lookback=*/500);
    for (size_t i = 0; i < bars.size(); ++i) {
        // Companion closes arrive first; the primary bar snapshots them into
        // the aligned buffer (carry-forward model).
        if (i < spy.size()) calc.updateCompanion("SPY", spy[i]);
        if (i < amd.size()) calc.updateCompanion("AMD", amd[i]);
        calc.update(bars[i]);
    }

    if (!calc.isReady()) {
        std::fprintf(stderr, "calculator not ready (min bars %d, got %zu)\n",
                     calc.minBarsNeeded(), bars.size());
        return 2;
    }

    const auto values = calc.calculate();
    const auto& expected = fx.at("expected");

    const double rel_tol = 1e-4;
    const double abs_tol = 1e-4;
    int failures = 0;

    std::printf("%-16s %18s %18s %14s\n", "feature", "cpp", "python", "result");
    std::printf("--------------------------------------------------------------------\n");
    for (size_t i = 0; i < features.size(); ++i) {
        const std::string& name = features[i];
        const double cpp = values[i];
        if (!expected.contains(name)) {
            std::printf("%-16s %18.10f %18s %14s\n", name.c_str(), cpp,
                        "(no ref)", "SKIP");
            continue;
        }
        const double py = expected.at(name).get<double>();
        const bool both_nan = std::isnan(cpp) && std::isnan(py);
        const double diff = std::fabs(cpp - py);
        const double tol = abs_tol + rel_tol * std::fabs(py);
        const bool ok = both_nan || diff <= tol;
        if (!ok) ++failures;
        std::printf("%-16s %18.10f %18.10f %14s\n",
                    name.c_str(), cpp, py, ok ? "OK" : "MISMATCH");
    }
    std::printf("--------------------------------------------------------------------\n");

    if (failures) {
        std::printf("FAILED: %d feature(s) did not match the notebook formulas\n",
                    failures);
        return 1;
    }
    std::printf("PASSED: all %zu features match the notebook formulas\n",
                features.size());
    return 0;
}
