// Verifies HMMRegime reproduces the causal online forward filter over a
// full-covariance GaussianHMM. Reads tests/hmm_fixture.json (generated by
// gen_hmm_expected.py), replays the daily feature sequence, and checks each
// day's regime against the numpy ground truth.

#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

#include "engine/HMMRegime.hpp"

using nlohmann::json;
using hermes::HMMRegime;

int main(int argc, char* argv[]) {
    const std::string path = argc > 1 ? argv[1] : "tests/hmm_fixture.json";
    std::ifstream in(path);
    if (!in) {
        std::fprintf(stderr, "could not open fixture '%s'\n", path.c_str());
        return 2;
    }
    json fx;
    in >> fx;

    // The fixture is a superset of the hmm_params schema — load the params
    // straight from it.
    HMMRegime hmm = HMMRegime::fromJsonString(fx.dump());

    std::vector<std::vector<double>> days;
    for (const auto& d : fx.at("days")) days.push_back(d.get<std::vector<double>>());
    std::vector<int> expected = fx.at("expected_states").get<std::vector<int>>();

    int failures = 0;
    std::printf("%4s %8s %8s %8s\n", "day", "cpp", "python", "result");
    std::printf("------------------------------------\n");
    for (size_t t = 0; t < days.size(); ++t) {
        const int got = hmm.observeDay(days[t]);
        const bool ok = got == expected[t];
        if (!ok) ++failures;
        std::printf("%4zu %8d %8d %8s\n", t, got, expected[t],
                    ok ? "OK" : "MISMATCH");
    }
    std::printf("------------------------------------\n");
    if (failures) {
        std::printf("FAILED: %d day(s) mismatched the reference filter\n", failures);
        return 1;
    }
    std::printf("PASSED: all %zu days match the reference forward filter\n",
                days.size());
    return 0;
}
