// Verifies FeatureCalculator produces values identical to the Ananke Python
// SDK (ananke.indicators). Reads tests/feature_fixture.json (generated by
// gen_expected.py), runs the calculator over the same bars, and compares each
// feature at the last bar against the SDK ground truth.

#include <chrono>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

#include "engine/FeatureCalculator.hpp"

using nlohmann::json;
using hermes::Bar;
using hermes::FeatureCalculator;

int main(int argc, char* argv[]) {
    const std::string path =
        argc > 1 ? argv[1] : "tests/feature_fixture.json";

    std::ifstream in(path);
    if (!in) {
        std::fprintf(stderr, "could not open fixture '%s'\n", path.c_str());
        return 2;
    }
    json fx;
    in >> fx;

    // Build bars from the fixture.
    std::vector<Bar> bars;
    for (const auto& b : fx.at("bars")) {
        Bar bar;
        bar.time = std::chrono::system_clock::from_time_t(b.at("t").get<long>());
        bar.open = b.at("open");
        bar.high = b.at("high");
        bar.low = b.at("low");
        bar.close = b.at("close");
        bar.volume = b.at("volume");
        bar.symbol = "TEST";
        bars.push_back(bar);
    }

    // Feature order matches the expected keys; lookback large enough to hold
    // the whole series so recursive seeding matches the SDK exactly.
    const std::vector<std::string> features = {
        "rsi_14", "ema_9", "ema_21", "sma_20", "atr_14",
        "volume_ratio", "logret_5", "intraday_range", "overnight_gap",
        "vwap_distance",
    };

    FeatureCalculator calc(features, /*lookback=*/500);
    for (const auto& bar : bars) calc.update(bar);

    if (!calc.isReady()) {
        std::fprintf(stderr, "calculator not ready (min bars %d, got %zu)\n",
                     calc.minBarsNeeded(), bars.size());
        return 2;
    }

    const auto values = calc.calculate();
    const auto& expected = fx.at("expected");

    const double rel_tol = 1e-4;
    const double abs_tol = 1e-4;
    int failures = 0;

    std::printf("%-16s %18s %18s %14s\n", "feature", "cpp", "python", "result");
    std::printf("--------------------------------------------------------------------\n");
    for (size_t i = 0; i < features.size(); ++i) {
        const std::string& name = features[i];
        const double cpp = values[i];
        const double py = expected.at(name).get<double>();
        const double diff = std::fabs(cpp - py);
        const double tol = abs_tol + rel_tol * std::fabs(py);
        const bool ok = diff <= tol;
        if (!ok) ++failures;
        std::printf("%-16s %18.10f %18.10f %14s\n",
                    name.c_str(), cpp, py, ok ? "OK" : "MISMATCH");
    }
    std::printf("--------------------------------------------------------------------\n");

    if (failures) {
        std::printf("FAILED: %d feature(s) did not match the Ananke SDK\n", failures);
        return 1;
    }
    std::printf("PASSED: all %zu features match the Ananke SDK\n", features.size());
    return 0;
}
