/**
 * Generate the Python snippet that reproduces the exact query the user is
 * viewing in the UI.
 *
 * The snippet is a single self-healing one-liner backed by the Ananke SDK's
 * get_data(): it returns a Kairos-ready DataFrame and, if the data is missing
 * (fresh DB, wiped table, never-pulled range), backfills it through the Spring
 * Boot API and shows a progress bar — all invisible to the user. The line never
 * changes between sessions. See ananke-sdk/ananke/data.py and
 * Dev-notes/get_data_build_instructions.md.
 */
export interface PythonExportParams {
  symbol: string;
  from: string; // ISO-8601 UTC (Z) — passed straight to get_data
  to: string; // ISO-8601 UTC (Z)
  interval: string;
  columns?: string[];
}

// get_data returns OHLCV by default. Only emit a columns=[...] kwarg when the
// selection differs from this set.
const OHLCV_DEFAULT = ["open", "high", "low", "close", "volume"];

export function buildPythonSnippet(p: PythonExportParams): string {
  const interval = mapIntervalToSnippet(p.interval);
  const columnsKwarg = buildColumnsKwarg(p.columns);
  return `# Generated by Ananke
# symbol=${p.symbol}  interval=${p.interval}
# range: ${p.from} -> ${p.to}
from ananke import get_data

df = get_data("${p.symbol}", "${p.from}", "${p.to}", "${interval}"${columnsKwarg})
df.head()
`;
}

export function buildJupyterTemplate(p: PythonExportParams): string {
  const interval = mapIntervalToSnippet(p.interval);
  const columnsKwarg = buildColumnsKwarg(p.columns);
  const date = new Date().toISOString().slice(0, 10);
  return `# Generated by Ananke — ${date}
# Symbol: ${p.symbol}  Interval: ${p.interval}
# Range: ${p.from} → ${p.to}

from ananke import get_data, Kairos
from ananke.indicators import rsi, sma, ema, bollinger, macd, atr, vwap

# --- Load Data -----------------------------------------------------------------
# get_data fetches from the Ananke backend and self-heals missing ranges by
# backfilling through the API (shows a progress bar). Same line every session.
df = get_data("${p.symbol}", "${p.from}", "${p.to}", "${interval}"${columnsKwarg})
print(df.head())
print(f"Rows: {len(df):,}")

# --- Define Your Strategy ------------------------------------------------------
s = Kairos(df, name="${p.symbol.toLowerCase()}_strategy")

# Add your entry conditions here:
# rsi_vals = rsi(df['close'], 14)
# s.enter_long(condition=rsi_vals < 30)
# s.enter_short(condition=rsi_vals > 70)
# s.exit_trade(stop_loss=0.02, take_profit=0.05)

# Run and view results:
# results = s.run()
# results

# Export to dashboard:
# s.export()
`;
}

/**
 * Build the optional `columns=[...]` kwarg for get_data().
 *
 * - `time` is always the DataFrame index in get_data — never a column — so it
 *   is dropped.
 * - When the remaining selection is exactly the default OHLCV set, the kwarg is
 *   omitted entirely for a clean one-liner.
 */
function buildColumnsKwarg(columns?: string[]): string {
  if (!columns || columns.length === 0) return "";
  const cols = columns.filter((c) => c !== "time");
  const isDefault =
    cols.length === OHLCV_DEFAULT.length && OHLCV_DEFAULT.every((c) => cols.includes(c));
  if (isDefault) return "";
  return `, columns=[${cols.map((c) => `"${c}"`).join(", ")}]`;
}

/**
 * Map the frontend Interval enum to the SDK's lowercase snippet form.
 * (1Min → 1min, 1Hour → 1hour, 1Day → 1day, …)
 */
function mapIntervalToSnippet(interval: string): string {
  switch (interval) {
    case "1Min":
      return "1min";
    case "5Min":
      return "5min";
    case "15Min":
      return "15min";
    case "30Min":
      return "30min";
    case "1Hour":
      return "1hour";
    case "1Day":
      return "1day";
    default:
      return "1min";
  }
}
