/**
 * Generate a Python (pandas + SQLAlchemy) snippet that reproduces the
 * exact query the user is currently viewing in the UI.
 *
 * Assumes the TimescaleDB schema documented in the backend README:
 *   table:    stock_prices  (hypertable)
 *   columns:  time, symbol, open, high, low, close, volume, vwap, trade_count
 *   pk:       (time, symbol)
 */
export interface PythonExportParams {
  symbol: string;
  from: string; // ISO
  to: string;   // ISO
  interval: string;
  columns?: string[];
}

const ALL_COLS = ["time", "symbol", "open", "high", "low", "close", "volume", "vwap", "trade_count"];

export function buildPythonSnippet(p: PythonExportParams): string {
  const cols = (p.columns && p.columns.length > 0 ? p.columns : ALL_COLS).join(", ");
  return `# Generated by Quant Trading Platform
# Query mirrors the chart/data view: symbol=${p.symbol}, interval=${p.interval}
# Range: ${p.from}  →  ${p.to}
import os
import pandas as pd
from sqlalchemy import create_engine, text

# --- Connection ---------------------------------------------------------------
# Override via env, or edit the default below.
CONN_STR = os.environ.get(
    "TIMESCALE_URL",
    "postgresql+psycopg2://postgres:postgres@localhost:5432/stockdb",
)
engine = create_engine(CONN_STR)

# --- Query --------------------------------------------------------------------
SQL = text("""
    SELECT ${cols}
    FROM stock_prices
    WHERE symbol = :symbol
      AND time >= :from_ts
      AND time <  :to_ts
    ORDER BY time ASC
""")

params = {
    "symbol":  "${p.symbol}",
    "from_ts": "${p.from}",
    "to_ts":   "${p.to}",
}

with engine.connect() as conn:
    df = pd.read_sql(SQL, conn, params=params, parse_dates=["time"])

# Resample to requested interval (${p.interval}) — matches the chart bucketing.
# Comment this out if you want raw bars.
RULE = ${JSON.stringify(intervalToPandasRule(p.interval))}
if RULE:
    df = (
        df.set_index("time")
          .groupby("symbol")
          .resample(RULE)
          .agg({
              "open":   "first",
              "high":   "max",
              "low":    "min",
              "close":  "last",
              "volume": "sum",
          })
          .dropna()
          .reset_index()
    )

print(df.head())
print(f"Rows: {len(df):,}")
df  # noqa: B018  (display in Jupyter)
`;
}

export function buildJupyterTemplate(p: PythonExportParams): string {
  const rule = intervalToPandasRule(p.interval);
  const date = new Date().toISOString().slice(0, 10);
  return `# Generated by Ananke — ${date}
# Symbol: ${p.symbol}  Interval: ${p.interval}
# Range: ${p.from} → ${p.to}

import os
import pandas as pd
from sqlalchemy import create_engine, text
from ananke import Kairos
from ananke.indicators import rsi, sma, ema, bollinger, macd, atr, vwap

# --- Database Connection -------------------------------------------------------
CONN_STR = os.environ.get(
    "TIMESCALE_URL",
    "postgresql+psycopg2://postgres:postgres@localhost:5432/stockdb",
)
engine = create_engine(CONN_STR)

# --- Load Data -----------------------------------------------------------------
SQL = text("""
    SELECT time, symbol, open, high, low, close, volume, vwap, trade_count
    FROM stock_prices
    WHERE symbol = :symbol
      AND time >= :from_ts
      AND time <  :to_ts
    ORDER BY time ASC
""")
params = {
    "symbol":  "${p.symbol}",
    "from_ts": "${p.from}",
    "to_ts":   "${p.to}",
}
with engine.connect() as conn:
    df = pd.read_sql(SQL, conn, params=params, parse_dates=["time"])

# Resample to ${p.interval}
RULE = "${rule}"
if RULE:
    df = (
        df.set_index("time")
          .groupby("symbol")
          .resample(RULE)
          .agg({"open": "first", "high": "max",
                "low": "min", "close": "last", "volume": "sum"})
          .dropna()
          .reset_index()
    )

print(df.head())
print(f"Rows: {len(df):,}")

# --- Define Your Strategy ------------------------------------------------------
s = Kairos(df, name="${p.symbol.toLowerCase()}_strategy")

# Add your entry conditions here:
# rsi_vals = rsi(df['close'], 14)
# s.enter_long(condition=rsi_vals < 30)
# s.enter_short(condition=rsi_vals > 70)
# s.exit_trade(stop_loss=0.02, take_profit=0.05)

# Run and view results:
# results = s.run()
# results

# Export to dashboard:
# s.export()
`;
}

function intervalToPandasRule(interval: string): string {
  switch (interval) {
    case "1Min": return "1min";
    case "5Min": return "5min";
    case "15Min": return "15min";
    case "30Min": return "30min";
    case "1Hour": return "1H";
    case "1Day": return "1D";
    default: return "";
  }
}
