/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BackfillJobStatus = "CANCELLED" | "COMPLETED" | "FAILED" | "PENDING" | "RUNNING";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type StrategyStatus = "ACTIVE" | "EXPORTED" | "STANDBY";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BackfillJobs {
  completedAt: Timestamp | null;
  completedChunks: Generated<number>;
  createdAt: Generated<Timestamp>;
  currentChunkFrom: Timestamp | null;
  currentChunkTo: Timestamp | null;
  errorMessage: string | null;
  failedAtChunk: number | null;
  fromTime: Timestamp;
  id: Generated<string>;
  startedAt: Timestamp | null;
  status: Generated<BackfillJobStatus>;
  symbol: string;
  totalBars: Generated<number>;
  totalChunks: Generated<number>;
  toTime: Timestamp;
  updatedAt: Generated<Timestamp>;
}

export interface BacktestResults {
  avgLoss: Numeric | null;
  avgWin: Numeric | null;
  createdAt: Generated<Timestamp>;
  equityCurve: Json | null;
  fromTs: Timestamp | null;
  id: Generated<Int8>;
  interval: Generated<string>;
  largestLoss: Numeric | null;
  largestWin: Numeric | null;
  losingTrades: number | null;
  maxDrawdown: Numeric | null;
  profitFactor: Numeric | null;
  sharpeRatio: Numeric | null;
  strategyId: Int8 | null;
  symbol: string | null;
  totalPnl: Numeric | null;
  totalPnlPct: Numeric | null;
  totalTrades: number | null;
  toTs: Timestamp | null;
  trades: Json | null;
  winningTrades: number | null;
  winRate: Numeric | null;
}

export interface StockPrices {
  close: Numeric;
  high: Numeric | null;
  low: Numeric | null;
  open: Numeric | null;
  symbol: string;
  time: Timestamp;
  tradeCount: number | null;
  volume: Int8 | null;
  vwap: Numeric | null;
}

export interface Strategies {
  createdAt: Generated<Timestamp>;
  definition: Json;
  deployMode: string | null;
  description: string | null;
  id: Generated<Int8>;
  name: string;
  status: Generated<StrategyStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface SymbolCoverage {
  fromTime: Timestamp;
  symbol: string;
  toTime: Timestamp;
}

export interface TrackedSymbols {
  createdAt: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<Int8>;
  symbol: string;
}

export interface DB {
  backfillJobs: BackfillJobs;
  backtestResults: BacktestResults;
  stockPrices: StockPrices;
  strategies: Strategies;
  symbolCoverage: SymbolCoverage;
  trackedSymbols: TrackedSymbols;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const BackfillJobStatusArrayValues: [BackfillJobStatus, ...BackfillJobStatus[]] = ["CANCELLED","COMPLETED","FAILED","PENDING","RUNNING"];
export const StrategyStatusArrayValues: [StrategyStatus, ...StrategyStatus[]] = ["ACTIVE","EXPORTED","STANDBY"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.