/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BacktestingRouteImport } from './routes/backtesting'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DataRouteImport } from './routes/data'
import { Route as IndexRouteImport } from './routes/index'

const BacktestingRoute = BacktestingRouteImport.update({
  id: '/backtesting',
  path: '/backtesting',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/live': typeof LiveRoute
  '/metrics': typeof MetricsRoute
  '/models': typeof ModelsRoute
  '/backtesting': typeof BacktestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/live': typeof LiveRoute
  '/metrics': typeof MetricsRoute
  '/models': typeof ModelsRoute
  '/backtesting': typeof BacktestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/live': typeof LiveRoute
  '/metrics': typeof MetricsRoute
  '/models': typeof ModelsRoute
  '/backtesting': typeof BacktestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data' | '/live' | '/metrics' | '/models' | '/backtesting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data' | '/live' | '/metrics' | '/models' | '/backtesting'
  id: '__root__' | '/' | '/data' | '/live' | '/metrics' | '/models' | '/backtesting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  LiveRoute: typeof LiveRoute
  MetricsRoute: typeof MetricsRoute
  ModelsRoute: typeof ModelsRoute
  BacktestingRoute: typeof BacktestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/backtesting': {
      id: '/backtesting'
      path: '/backtesting'
      fullPath: '/backtesting'
      preLoaderRoute: typeof BacktestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  LiveRoute: LiveRoute,
  MetricsRoute: MetricsRoute,
  ModelsRoute: ModelsRoute,
  BacktestingRoute: BacktestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
